name: profiteer_client
dependencies:
  polymer: ">=0.13.0 <0.14.0"
  core_elements: ">=0.2.0 <0.3.0"
  browser: ">=0.10.0 <0.11.0"
  chrome: ">=0.6.0 <0.7.0"
transformers:
  - polymer:
      entry_points: web/index.html